# Generated by Django 4.1.13 on 2024-01-31 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=7)),
                ('height', models.FloatField()),
                ('motive', models.CharField(max_length=30)),
                ('bloodgrp', models.CharField(max_length=3)),
                ('medicalhistory', models.TextField()),
                ('activitylevel', models.CharField(max_length=30)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
