# Generated by Django 4.1.13 on 2024-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_data',
            name='exercise_id',
        ),
        migrations.AlterField(
            model_name='workout_data',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
