# Generated by Django 4.1.13 on 2024-03-23 23:34

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaAsana_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('steps', djongo.models.fields.JSONField()),
                ('image', models.CharField(max_length=255)),
                ('benefits', djongo.models.fields.JSONField()),
                ('limitations', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe_data',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
