# Generated by Django 4.1.13 on 2024-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_userinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('portion_size', models.CharField(max_length=50)),
                ('calorie', models.IntegerField()),
            ],
        ),
    ]
