# Generated by Django 4.1.13 on 2024-02-10 08:46

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_workoutdairy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdairy',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='workoutdairy',
            name='workoutname',
        ),
        migrations.AddField(
            model_name='workoutdairy',
            name='workout',
            field=djongo.models.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
