# Generated by Django 4.1.13 on 2024-02-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_remove_workoutdairy_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', djongo.models.fields.JSONField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
