# Generated by Django 4.1.13 on 2024-03-11 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_mealdairy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealdairy',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealdairy',
            name='breakfast',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mealdairy',
            name='dinner',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mealdairy',
            name='lunch',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Steps', models.IntegerField()),
                ('SleepTime', models.IntegerField()),
                ('Water', models.FloatField()),
                ('Weight', models.FloatField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalorieManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calIntake', models.FloatField()),
                ('calBurned', models.FloatField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
