# Generated by Django 4.1.13 on 2024-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_mealdairy_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='weight',
            new_name='currentWeight',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='bloodgrp',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='medicalhistory',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='targetWeight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
