# Generated by Django 4.1.13 on 2024-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0012_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='currentWeight',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='height',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='targetWeight',
            field=models.CharField(max_length=6),
        ),
    ]
